apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-cpu-poc
  labels:
    app: vllm-cpu-poc

spec:
  selector:
    matchLabels:
      app: vllm-cpu-poc
  replicas: 1
  template:
    metadata:
      name: vllm-cpu-poc
      labels:
        app: vllm-cpu-poc
    spec:
      volumes:
        - name: mem-lock
          emptyDir:
            medium: Memory
            sizeLimit: "4Gi"
        - name: vllm-storage
          persistentVolumeClaim:
            claimName: vllm-pvc
      initContainers:
      - name: model-download-container
        image: continuumio/miniconda3:latest
        volumeMounts:
          - name: vllm-storage
            mountPath: /workspace/model
        command: ["/bin/sh", "-c"]
        args:
          - |
            conda install -y conda-forge::huggingface_hub
            hf download HuggingFaceTB/SmolLM2-135M-Instruct --local-dir /workspace/model 
      containers:
      - name: vllm-container
        image: vllm/vllm-openai-cpu:latest-x86_64
        ports:
        - containerPort: 8000
        env:
        - name: HF_HUB_OFFLINE
          value: "1"
        volumeMounts:
        - name: mem-lock
          mountPath: /dev/shm
        - name: vllm-storage
          mountPath: /workspace/model
        args:
        - "--model"
<<<<<<< Updated upstream
        - "/workspace/model"  # Point directly to the local folder containing the weights
        - "--served-model-name"
        - "HuggingFaceTB/SmolLM2-135M-Instruct" # Exposes the clean name to your API queries
        - "--device"
        - "cpu"
=======
        - "/workspace/model"
        - "--served-model-name"
        - "HuggingFaceTB/SmolLM2-135M-Instruct"
>>>>>>> Stashed changes
        - "--dtype"
        - "float32"
        - "--max-model-len"
        - "2048"
        - "--gpu-memory-utilization"
        - "0.5"
