apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-pvc
  labels:
    app: vllm-pvc
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: longhorn
  volumeName: ontap-nfs
  resources:
    requests:
      storage: 10Gi
