apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-pvc
  labels:
    app: vllm-pvc
spec:
  accessModes: 
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi